name: reviews 

on:
  pull_request:
    #types: [opened] TODO UNCOMMENT BEFORE MERGE



jobs:
  add-devtools-reviewers:
    name: Add Devtools Reviewers
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - name: Get Pull Request Number
      id: get-pull-request-number
      run: |
        PULL_REQUEST_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        echo "::set-output name=PULL_REQUEST_NUMBER::$PULL_REQUEST_NUMBER"
    - name: Add reviewers
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PULL_NUMBER: ${{steps.get-pull-request-number.outputs.PULL_REQUEST_NUMBER}}
        HUB_VERBOSE: 1
      run: |
        RESPONSE=$(jq -n '{"team_reviewers": ["devtools-reviewers"], "reviewers": []}' | gh api  /repos/flutter/devtools/pulls/$PULL_NUMBER/requested_reviewers -X POST --input -)
        echo $RESPONSE | jq .