name: reviews 

on:
  pull_request:
    #types: [opened] TODO UNCOMMENT BEFORE MERGE



jobs:
  add-devtools-reviewers:
    name: Add Devtools Reviewers
    runs-on: ubuntu-latest
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      issues: write
      discussions: write
      packages: write
      pages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    steps:
    - name: Get Pull Request Number
      id: get-pull-request-number
      run: |
        PULL_REQUEST_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        echo "::set-output name=PULL_REQUEST_NUMBER::$PULL_REQUEST_NUMBER"
    - name: Add reviewers
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PULL_NUMBER: ${{steps.get-pull-request-number.outputs.PULL_REQUEST_NUMBER}}
      run: |
        export HUB_VERBOSE=1
        jq -n '{"team_reviewers": ["devtools-reviewers"], "reviewers": []}' | gh api  /repos/flutter/devtools/pulls/$PULL_NUMBER/requested_reviewers -X POST --input -